server:
  port: 9089

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: get-book-service
          uri: lb://get-book-service
          predicates:
            - Path=/get/**

        - id: add-book-service
          uri: lb://add-book-service
          predicates:
            - Path=/add/**
